### ISSUE TITLE
Wrong `.add()` behavior

### ISSUE THREAD

**Issue by darioielardi** [dayjs/day.dart#40]
With day.js, the following operation: `dayjs('2020-08-31').add(1, 'month')` outputs `2020-09-30`, because it never exceeds the month's last day (if "month" is the unit), even if August has 31 days and September only 30.

In day.dart, the output of `Day.fromString('2020-08-31').add(1, 'month')` is `2020-10-01`.

**Comment by g1eny0ung** [comment]
This is because dart's `DataTime` will automatically convert the overflow date. Put another way, `DataTime` in the standard library is much more accurate.

I want the default `.add()` behavior to be closer to the standard library, so I'd prefer to go ahead and add a new method to solve this problem, like `.addRound()`. What do you think?

**Comment by darioielardi** [comment]
Sorry I thought the goal of day.dart was to mirror the day.js api, if that's not the case an `.addRound()` method looks good! I suggest putting this difference in the `.add()` docs though, cause who's coming from day.js expects the same behavior.

**Comment by g1eny0ung** [comment]
@darioielardi I'm already finishing the implementation of `.addRound()` and will release a new version soon. Thank you for spotting the problem!
